### PR TITLE
Upgrade Gradle to 5.2

### PR DESCRIPTION
**Pull request by jaredsburrows**

### CODE REVIEW

**Comment by kirich1409** [comment]
Hi. Do you have plans to finish with the PR ? I made another PR where i update Gradle to 5.2.1 and fix tests https://github.com/jaredsburrows/gradle-license-plugin/pull/68

It's critical for me, because the previous version isn't compatible with Gradle 5.X and I can't migrate to Android Studio 3.4

**Comment by jaredsburrows** [comment]
@kirich1409 I want to. I have to update the tests. Your Pr is failing because it is using the old test way `.execute()`.

**Comment by kirich1409** [comment]
Issue is not calling execute(). I fixed all unit tests and rebase on the latest master branch.

Issue on Travis CI is Missed component  build-tools;28.0.3 Android SDK Build-Tools 28.0.3

**Comment by jaredsburrows** [comment]
@kirich1409 Your branch is still failing.

**Comment by kirich1409** [comment]
I know. The reason is the environment on CI: no `build-tools;28.0.3 Android SDK Build-Tools 28.0.3` component

**Comment by jaredsburrows** [comment]
There has to be another underlying problem. I have other tests using the
Android plugin that do not use buildToolsVersion. The Android Gradle plugin
downloads this automatically.

Jared Burrows

*jaredsburrows@gmail.com <jaredsburrows@gmail.com>*
LinkedIn: https://www.linkedin.com/in/jaredsburrows

**Pull request merged**
