### PR TITLE
issue #26 Recursively scan parent POMs for license

### PR DESCRIPTION
**Pull request by ChristianCiach**
Related to pull request #23

### CODE REVIEW

**Comment by ChristianCiach** [comment]
References issue #26

**Comment by ChristianCiach** [comment]
Dammit, I accidently push both changes to the same branch/pull request again! 

Well, you said that you don't mind. And this time the commits have the correct author, so I will leave it like this. I will now take a look at the README.

**Comment by jaredsburrows** [comment]
Thanks!

**Comment by jaredsburrows** [comment]
This should close https://github.com/jaredsburrows/gradle-license-plugin/issues/15 and https://github.com/jaredsburrows/gradle-license-plugin/issues/26.

**Comment by ChristianCiach** [comment]
@jaredsburrows 
Regarding this point:
> Maybe add a test with one of the Square libraries to test the parent POM search?

I not fluent enough with Groovy to comfortably write a new unit test (more accurate: "I don't wanna"), so I've changed the current POM-structure for the existing parent-POM-test with an additional grandparent-POM that contains the actual license information. This unit test still succeeds, to this should confirm that recursive parent POM search works.

**Comment by jaredsburrows** [comment]
@ChristianCiach Thanks for that!

**Pull request merged**
