### PR TITLE
Update html css to support word-breaking on long lines

### PR DESCRIPTION
**Pull request by kgbier**
# Reason
Some long URL's fail to break into multiple lines forcing the resulting HTML page to turn on horizontal scrolling on small screens.

# Solution
A minor update to the HTML CSS to add `word-break: break-word` to preformatted blocks, ensuring no long lines will push the page beyond the viewport.

Thanks for your work on this plugin!

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Thanks! Do you mind include a before and after screenshot?

**Comment by jaredsburrows** [comment]
Can you resolve conflicts so I can merge?

**Comment by jaredsburrows** [comment]
Bump

**Comment by nisrulz** [comment]
@jaredsburrows should I take this up? I would open a new PR with the same changes. I would like these changes to be merged?

Obviously will credit the PR author, since I will only copy paste it.

**Comment by jaredsburrows** [comment]
@nisrulz  Sounds good, can you share before/after screenshots?

**Comment by nisrulz** [comment]
I'll fix the conflicts and open a new PR with the screenshots 🚀

**Comment by nisrulz** [comment]
@jaredsburrows We should close this PR and use PR #159 for further discussion.

**Comment by jaredsburrows** [comment]
@nisrulz Sure, you can close it.

**Comment by nisrulz** [comment]
I actually can't. This is not my PR. Only the owner, you, can close it.

**Pull request closed without merging**
