### PR TITLE
Updated the readme version

### PR DESCRIPTION
**Pull request by PaulWoitaschek**

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Thanks

**Comment by jaredsburrows** [comment]
Why down grade?

**Comment by PaulWoitaschek** [comment]
Because 42 is larger than 7?

**Comment by PaulWoitaschek** [comment]
You are versioning wrong. Look up semver. 

For example here the 42 is listed as the latest version because 42 > 7
https://plugins.gradle.org/plugin/com.jaredsburrows.license

**Comment by jaredsburrows** [comment]
@PaulWoitaschek Thanks. I fixed the versioning [here](https://github.com/jaredsburrows/gradle-license-plugin/commit/8a59374677c43266b8a4e87155347f8711b83cb7).

**Comment by PaulWoitaschek** [comment]
Following semver it's major.mimor.patch

You make breaking changes: major goes up. 
You add new stuff: minor goes up. 
You fix something: patch goes up

There is nothing wrong with sth like 0.10.0 following 0.9.x

https://semver.org/

**Comment by jaredsburrows** [comment]
Yes. I should not have added a 2 after .4. This is will be fixed for now on.

**Pull request merged**
