### PR TITLE
Update html css to support word-breaking on long lines

### PR DESCRIPTION
**Pull request by nisrulz**
This is a duplicate PR of #101. The old PR is abandoned and has conflicts, thus creating a new one.

This work was originally done by  @kgbier

TODO: 

- [ ] Add screenshots

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Sync and add screenshots?

**Comment by nisrulz** [comment]
@jaredsburrows I have synced and removed all conflicts from this branch.

I remember I wasn't sure how to take the screenshots in this case. 

Wouldn't you say that this repo needs to have a sample app to demonstrate the integration, thus enabling even taking automated screenshots for each PR?

I am not sure how to feed in the plugin in this case, where the plugin code is modified. I understand the `mavenLocal` publishing when dealing with Android libs and that would allow me to publish the modified code to my own local maven repo. Then I can load the plugin from my local system, to generate the screenshot. 

Since this is a plugin, I am not sure. Maybe some pointers how you would do that would help me.

**Comment by jaredsburrows** [comment]
Sorry for the churn, is `break-word` deprecated? See: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break.

**Comment by nisrulz** [comment]
Interesting. I didn't know that. Let me look into it. Will update it here.

**Comment by nisrulz** [comment]
I think the deprecated property is supposed to be still used since the alternatives might only work on latest versions. The deprecated property will keep working for sometime, considering the webkit on Android is usually not updated across all Android versions.

Here is Chrome platform mentioning some info on the alternative (https://chromestatus.com/feature/5126089347170304):
> The CSS Text 3 spec still allows the 'break-word' value to ensure compatibility (Safari and Chrome support it), but its marked as deprecated; that's why Firefox doesn't implement it.
>
>The 'word-break: break-word' feature provides a behavior that web authors really appreciate, which consist on breaking opportunities account for the min-content size. 
>
>Several approaches have been explored, but all of them lead to serious web compatibility issues, so that the CSS WG resolved that a new CSS value should be the best solution.

**Comment by jaredsburrows** [comment]
Thanks!

**Pull request merged**
