### PR TITLE
Fix for #52 - Eliminate Duplicate Licenses

### PR DESCRIPTION
**Pull request by iankerr**
This is is a proposed fix for issue #52 

I changed the HtmlReport class a bit to lookup licenses in the license map by url and name, and group them all together in the report.

Also:
-adds <a name /> elements for all licenses (including "no license) - not just the ones in the license map
-updates tests to reflect my changes
-adds more names/urls for the Apache 2.0 license
-adds the CC0 1.0 Universal license to the map

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@iankerr Since I merged your other PR, can you fix your conflicts?

**Comment by iankerr** [comment]
Hmmm... I merged in your recent changes, and now the build is failing.

Error: "Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-3.4-bin.zip'"

Any idea what's wrong?

**Comment by jaredsburrows** [comment]
Sorry. I merged without fixing the build. Do you mind pushing this back up so we can merge it?

**Comment by iankerr** [comment]
I've re-created the pull request: https://github.com/jaredsburrows/gradle-license-plugin/pull/57 ...hopefully that's what you're asking for?

**Pull request merged**
